# Generated by Django 3.2.8 on 2021-11-03 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anualista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField()),
                ('termino', models.DateTimeField(auto_now=True, null=True)),
                ('valor_ano', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Finalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Parametro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_dia', models.DecimalField(decimal_places=2, max_digits=4)),
                ('valor_mes', models.DecimalField(decimal_places=2, max_digits=5)),
                ('valor_ano', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('profissao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Mensalista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField()),
                ('termino', models.DateTimeField(auto_now=True, null=True)),
                ('valor_mes', models.DecimalField(decimal_places=2, max_digits=5)),
                ('finalidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.finalidade')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Diarista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField()),
                ('termino', models.DateTimeField(auto_now=True, null=True)),
                ('valor_dia', models.DecimalField(decimal_places=2, max_digits=4)),
                ('finalidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.finalidade')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='AtividadeMes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_mes', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pago', models.BooleanField(default=False)),
                ('finalidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.finalidade')),
                ('mensalista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.mensalista')),
            ],
        ),
        migrations.CreateModel(
            name='AtividadeDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_dia', models.DecimalField(decimal_places=2, max_digits=4)),
                ('pago', models.BooleanField(default=False)),
                ('diarista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.diarista')),
                ('finalidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.finalidade')),
            ],
        ),
        migrations.CreateModel(
            name='AtividadeAno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_ano', models.DecimalField(decimal_places=2, max_digits=6)),
                ('pago', models.BooleanField(default=False)),
                ('anualista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.anualista')),
                ('finalidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.finalidade')),
            ],
        ),
        migrations.AddField(
            model_name='anualista',
            name='finalidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.finalidade'),
        ),
        migrations.AddField(
            model_name='anualista',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.pessoa'),
        ),
    ]
