# Generated by Django 3.2.8 on 2021-11-03 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensalista',
            name='valor_mes',
        ),
    ]
