# Generated by Django 3.2.8 on 2021-11-03 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_mensalista_valor_mes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anualista',
            name='valor_ano',
        ),
        migrations.RemoveField(
            model_name='diarista',
            name='valor_dia',
        ),
    ]
