# Generated by Django 3.2.8 on 2021-11-03 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20211103_1003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anualista',
            name='finalidade',
        ),
    ]
