# Generated by Django 3.2.8 on 2021-11-14 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20211107_1326'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vitalista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField()),
                ('termino', models.DateTimeField(auto_now=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='AtividadeVital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_licenca', models.DecimalField(decimal_places=2, max_digits=6)),
                ('pago', models.BooleanField(default=False)),
                ('finalidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.finalidade')),
                ('vitalista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.vitalista')),
            ],
        ),
    ]
