# Generated by Django 3.2.8 on 2021-11-14 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_parametro_valor_licenca'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atividadevital',
            old_name='valor_licenca',
            new_name='valor_servico',
        ),
    ]
