# Generated by Django 3.2.8 on 2021-11-19 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_valor_servico_atividadevital_valor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pessoa',
            old_name='profissao',
            new_name='profissão',
        ),
    ]
