# Generated by Django 3.2.8 on 2021-11-21 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_profissao_pessoa_profissão'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pessoa',
            old_name='profissão',
            new_name='area_atuacao',
        ),
        migrations.AddField(
            model_name='pessoa',
            name='profissao',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
